fastlane_version '2.53.1'

desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'org.reactjs.native.example.weather-app', type: 'development', readonly: false)
  end

platform :ios do
  desc 'Build the iOS application.'
  lane :build do
    certificates
    gym(scheme: 'weather_app', project: './ios/weather_app.xcodeproj')
  end
end

platform :android do
  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')
  end
end
