name: React Native CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install_and_test:
    name: Install Dependencies, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Run Lint
        run: yarn lint

      - name: Run Jest Tests
        run: yarn test

  build_android:
    name: Build Android Application
    runs-on: ubuntu-latest
    needs: install_and_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Dependencies
        run: yarn install

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run Fastlane to Build Android
        run: fastlane android build

  # Uncomment the below section when ready to build iOS
  # build_ios:
  #   name: Build iOS Application
  #   runs-on: macos-latest
  #   needs: install_and_test
  #
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #
  #   - name: Set up Node.js
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '18'
  #
  #   - name: Install Yarn
  #     run: npm install -g yarn
  #
  #   - name: Install Dependencies
  #     run: yarn install
  #
  #   - name: Install Bundler
  #     run: gem install bundler
  #
  #   - name: Install CocoaPods
  #     run: bundle exec pod install --repo-update
  #
  #   - name: Run Fastlane to Build iOS
  #     run: fastlane ios build
